version: "3.8"
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres

    ports:
      - '5432:5432'
    volumes:
      - 
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/app
    
volumes:
    postgres: