graph LR

A[Start] --> B[Validate Token]
B --> |Valid| C[Check Password Match]
B --> |Invalid| D[Return 400 Bad Request]
C --> |Match| E[Generate Hash]
C --> |No Match| D[Return 400 Bad Request]
E --> F[Update User Password]
F --> G[Return User]
G --> H[End]
D --> H[End]